### ISSUE TITLE
Removing wild card (star) imports from files

### ISSUE THREAD

**Issue by Hunter2807** [pyunity/pyunity#26]

**Comment by Hunter2807** [comment]
https://github.com/pyunity/pyunity/blob/9f4c2675e9e9a66f5c2db7f5042d9e6277f23085/pyunity/physics/core.py
https://github.com/pyunity/pyunity/blob/33ef86db69b35665bf000a4d6df23b8604936494/tests.py
https://github.com/pyunity/pyunity/blob/babdfd55de0012a4bf6d7677999821b6b74811f3/pyunity/window/glfwWindow.py
https://github.com/pyunity/pyunity/blob/63b15f162d88b0976c3a5d477b681f218d2107a8/pyunity/scenes/sceneManager.py
https://github.com/pyunity/pyunity/blob/babdfd55de0012a4bf6d7677999821b6b74811f3/pyunity/window/templateWindow.py
https://github.com/pyunity/pyunity/blob/d0ec080f9406adef07956ded23f0751bde222d93/pyunity/scenes/scene.py
https://github.com/pyunity/pyunity/blob/d0233bffd7cdde59e325d63546f4ea9b51a6d6e6/pyunity/loader.py

For now these are the files that still have `from <module> import *` statement. Gonna fix them as soon as possible!

**Comment by Hunter2807** [comment]
Yo @rayzchen mind helping me with this one? Since I am lost lmao

**Comment by rayzchen** [comment]
not possible cus of how many different classes are imported. Tbh, i don't think this pr is necessary.
