### ISSUE TITLE
[OBSERVATION] Cool idea, but the name will likely get C&D'd....

### ISSUE THREAD

**Issue by hughperkins** [pyunity/pyunity#66]
Cool idea for a project :) I suspect that as far as the name there are two situations:
1. no-one is using your project, and it sits below the radar, and Unity themselves don't notice, or do anything
2. your project starts to become popular. I suspect your name will then get cease and desisted, by Unity, at that point

I suppose you could just change the name at that point, but, might be as easy to just change the name now? (e.g. Mono, which Unity uses, didn't call themselves "Linux .Net Framework", they called themselves "mono", and everyone knew that it was a cross platform version of the windows .net framework).

this would also avoid having to state twice, in the first two paragraphs of your front page, that pyunity is not a wrapper around unity :)

(And it's natural to assume pyunity is a wrapper. My pytorch project, https://github.com/hughperkins/pytorch (which predates the Facebook pytorch by a year or two), was a wrapper around Facebook's lua torch)

**Comment by hughperkins** [comment]
(by the way, I found the project, because I'm thinking of building a connector between python and unity, and searched the name `pyunity`, lol :P So I might be biased about the name :D )

**Comment by rayzchen** [comment]
The name doesn't seem to be conflicting with Guideline 3 of Unity "Wordmarks":
> 3. You may use Unity Wordmarks in all manner of published materials, digital and otherwise, provided > that your use is consistent with all of the following and otherwise complies with these Guidelines:
>    - using the Unity Wordmarks is actually relevant to the subject matter of the materials;
>    - the Unity Wordmarks do not figure more prominently in the materials than your Trademarks, including Trademarks of your products and services; and
>    - you provide a trademark notice as described in these Guidelines.
(taken from https://unity.com/legal/branding-trademarks)

However, maybe I'm interpreting that wrong, or I need to make some changes to where and how the name is used. Personally, I'm also attached to the name as well.

**Comment by hughperkins** [comment]
I mean, I'm not a lawyer. As long as few people are using the project, it seems likely that no-one will care/notice. And if it becomes well known, you could always rename it at that point.
